name: unit testing

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v3.2.0
      with:
        go-version: '>=1.18'

    - name: Check out code
      uses: actions/checkout@v3

    - name: Run unit tests
      run: go test ./...

    - name: Run race detector
      run: go test -race ./...
